
import express from "express";import TelegramBot from "node-telegram-bot-api";import {analyzeInput,status} from "./engine.js";import {analyzeBumper} from "./bumper.js";import {syncToday,syncUrl} from "./sync.js";
const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw Error("TELEGRAM_BOT_TOKEN missing");
const bot=new TelegramBot(token,{polling:false}),app=express(),port=Number(process.env.PORT||10000),secret=process.env.WEBHOOK_SECRET||"lotto-v10",admin=String(process.env.ADMIN_CHAT_ID||"").trim();app.use(express.json({limit:"2mb"}));
const g=v=>v==null?"Never":`${v} day${v===1?"":"s"}`,kb=()=>({reply_markup:{inline_keyboard:[[{text:"🔄 Catch-up Sync",callback_data:"sync_today"}],[{text:"📊 Status",callback_data:"status"}]]}}),isAdmin=id=>!admin||String(id)===admin;
function fmt(x){const p=x.p4;let s=`INPUT: ${x.input}\nAS OF: ${x.asOf}\n\n4-DIGIT ANALYSIS: ${x.four}\n`;s+=p.last?`Last seen: ${p.last.date} (${g(p.last.days)} ago)\n`:"Last seen: Never\n";s+=p.cooldown?"⚠️ 6-DAY COOLDOWN: ACTIVE\n":"✅ 6-DAY COOLDOWN: CLEAR\n";s+=`365d:${p.h365} | 180d:${p.h180} | 90d:${p.h90} | 30d:${p.h30} | All:${p.total}\nHistorical Strength:${p.score}/100\n\n🤖 ROBOT SUGGESTIONS\n`;if(!x.suggestions.length)s+="No strong nearby historical suggestion found.\n";else x.suggestions.forEach((c,i)=>s+=`${i+1}. ${c.s} — ${c.score}/100${i===0?" ★ BEST":""} | 365d:${c.h365} | All:${c.total} | Last:${c.last?g(c.last.days):"Never"}\n`);if(x.first){const f=x.first;s+=`\nFIRST-PRIZE 6D PATTERN\nStructure:${f.structure.score}/100 | Historical similarity:${f.simScore}/100 | Date/Numerology:${f.rootMatch}/100\nOverall:${f.score}/100\n${f.red?"🔴 RED ALERT — STRONG FIRST-PRIZE PATTERN MATCH":"No RED ALERT"}\n`;}return s;}
function fmtBumper(b,n){const p=b.p4,np=n.p4;let s=`INPUT: B${b.input}\nMODE: BUMPER\n\nBUMPER 4D: ${b.four}\nBumper hits:${p.total} | 365d:${p.h365} | 730d:${p.h730}\n`;s+=p.last?`Last bumper hit:${p.last.date} (${g(p.last.days)} ago)\n`:"Last bumper hit:Never\n";s+=`Last 2 bumper draws:${b.last2.join(", ")||"N/A"}\n${p.inLast2>0?"⚠️ RECENT BUMPER FILTER: BLOCKED":"✅ RECENT BUMPER FILTER: CLEAR"}\nBumper Strength:${p.score}/100\n\nNORMAL LOTTERY CROSS-CHECK\nNormal ${n.four}: 365d=${np.h365} | 180d=${np.h180} | 90d=${np.h90} | All=${np.total}\n`;s+=np.last?`Last normal hit:${np.last.date} (${g(np.last.days)} ago)\n`:"Last normal hit:Never\n";s+=np.cooldown?"⚠️ Normal 6-day cooldown: ACTIVE\n":"✅ Normal 6-day cooldown: CLEAR\n";s+="\n🤖 BUMPER ROBOT SUGGESTIONS\n";if(!b.suggestions.length)s+="No strong bumper suggestion found.\n";else b.suggestions.forEach((c,i)=>s+=`${i+1}. ${c.n} — ${c.score}/100${i===0?" ★ BEST":""} | hits:${c.total}\n`);if(b.first){const f=b.first;s+=`\nBUMPER FIRST-PRIZE 6D\nStructure:${f.structure.score}/100 | Similarity:${f.simScore}/100 | Date/Numerology:${f.rootMatch}/100\nOverall:${f.score}/100\n${f.red?"🔴 RED ALERT — STRONG BUMPER FIRST-PRIZE PATTERN":"No RED ALERT"}\n`;}return s;}
async function stat(id){const s=status();return bot.sendMessage(id,`BOT ONLINE — V10 VERIFIED\n4D rows:${s.fourHistoricalRows}\n4D unique:${s.fourUnique}\nFirst rows:${s.firstRows}\nSynced rows:${s.syncedRows}\nLatest any:${s.lastDate}\nLatest COMPLETE:${s.lastCompleteDate}`,kb());}
async function doSync(id){if(!isAdmin(id))return bot.sendMessage(id,"Sync admin-only.");await bot.sendMessage(id,"🔄 Catch-up sync starting...");const r=await syncToday();return bot.sendMessage(id,`${r.ok?"✅":"⚠️"} ${r.message}\nFrom:${r.from}\nTo:${r.to}\nResults found:${r.found}\nVerified:${r.verified}\nFailed:${r.failed}\n4D added:${r.added4}\nFirst added:${r.added1}\nBumpers:${(r.bumperRefresh||[]).join(", ")||"-"}\nDatabase latest:${r.databaseLatest}`,kb());}
async function handle(m){if(!m?.chat?.id)return;const id=m.chat.id;if(m.text==="/start")return bot.sendMessage(id,`Kerala Lottery V10 VERIFIED\nText only.\n4D / 6D / B4D / B6D supported.\nCatch-up sync included.`,kb());if(m.text==="/status")return stat(id);if(m.text==="/sync")return doSync(id);if(m.text?.startsWith("/syncurl ")){if(!isAdmin(id))return;try{const r=await syncUrl(m.text.slice(9).trim());return bot.sendMessage(id,`✅ URL verified/synced ${r.draw_date} ${r.draw_no} | 4D:${r.added4} | First:${r.added1}`,kb());}catch(e){return bot.sendMessage(id,`❌ ${e.message}`);}}if(m.text){const bv=[...m.text.toUpperCase().matchAll(/\bB(\d{4}|\d{6})\b/g)].map(x=>x[1]);if(bv.length){for(const v of bv){const b=analyzeBumper(v,new Date()),n=analyzeInput(v,new Date());if(b&&n)await bot.sendMessage(id,fmtBumper(b,n),kb());}return;}for(const v of [...m.text.matchAll(/\b(\d{4}|\d{6})\b/g)].map(x=>x[1])){const a=analyzeInput(v,new Date());if(a)await bot.sendMessage(id,fmt(a),kb());}}}
async function cb(q){const id=q.message?.chat?.id;if(!id)return;try{await bot.answerCallbackQuery(q.id);}catch{}if(q.data==="sync_today")return doSync(id);if(q.data==="status")return stat(id);}
app.get("/",(_,r)=>r.send("V10 VERIFIED ONLINE"));app.get("/health",(_,r)=>r.json({ok:true,...status()}));app.post(`/telegram/${secret}`,(req,res)=>{res.sendStatus(200);if(req.body?.callback_query)cb(req.body.callback_query).catch(console.error);else handle(req.body?.message).catch(console.error);});
app.listen(port,"0.0.0.0",async()=>{const u=process.env.RENDER_EXTERNAL_URL;if(u)try{await bot.setWebHook(`${u.replace(/\/$/,"")}/telegram/${secret}`);}catch{}console.log("ONLINE",status());});
