
import express from "express";import TelegramBot from "node-telegram-bot-api";import {analyzeInput,status} from "./engine.js";import {syncToday,syncUrl} from "./sync.js";
const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw Error("TELEGRAM_BOT_TOKEN missing");
const bot=new TelegramBot(token,{polling:false}),app=express(),port=Number(process.env.PORT||10000),secret=process.env.WEBHOOK_SECRET||"lotto-v7-text",admin=String(process.env.ADMIN_CHAT_ID||"").trim();app.use(express.json({limit:"2mb"}));
const g=v=>v==null?"Never":`${v} day${v===1?"":"s"}`,kb=()=>({reply_markup:{inline_keyboard:[[{text:"🔄 Sync Today",callback_data:"sync_today"}],[{text:"📊 Status",callback_data:"status"}]]}}),isAdmin=id=>!admin||String(id)===admin;
function fmt(x){const p=x.p4;let s=`INPUT: ${x.input}\nAS OF: ${x.asOf}\n\n4-DIGIT ANALYSIS: ${x.four}\n`;s+=p.last?`Last seen: ${p.last.date} (${g(p.last.days)} ago)\n`:"Last seen: Never\n";s+=p.cooldown?"⚠️ 6-DAY COOLDOWN: ACTIVE\n":"✅ 6-DAY COOLDOWN: CLEAR\n";s+=`365d:${p.h365} | 180d:${p.h180} | 90d:${p.h90} | 30d:${p.h30} | All:${p.total}\nHistorical Strength:${p.score}/100\n\n🤖 ROBOT SUGGESTIONS\n`;if(!x.suggestions.length)s+="No strong nearby historical suggestion found.\n";else x.suggestions.forEach((c,i)=>s+=`${i+1}. ${c.s} — ${c.score}/100${i===0?" ★ BEST":""} | 365d:${c.h365} | All:${c.total} | Last:${c.last?g(c.last.days):"Never"}\n`);if(x.first){const f=x.first;s+=`\nFIRST-PRIZE 6D PATTERN\nStructure:${f.structure.score}/100 | Historical similarity:${f.simScore}/100 | Date/Numerology:${f.rootMatch}/100\nOverall:${f.score}/100\n${f.red?"🔴 RED ALERT — STRONG FIRST-PRIZE PATTERN MATCH":"No RED ALERT"}\n`;}return s;}
async function stat(id){const s=status();return bot.sendMessage(id,`BOT ONLINE\n4D rows:${s.fourHistoricalRows}\n4D unique:${s.fourUnique}\nFirst rows:${s.firstRows}\nSynced:${s.syncedRows}\nLatest:${s.lastDate}`,kb());}
async function doSync(id){if(!isAdmin(id))return bot.sendMessage(id,"Sync admin-only.");await bot.sendMessage(id,"🔄 Full sync starting...");const r=await syncToday();return bot.sendMessage(id,`${r.ok?"✅":"⚠️"} ${r.message}\nPages:${r.pages}\n4D added:${r.added4}\nFirst added:${r.added1}`,kb());}
async function handle(m){if(!m?.chat?.id)return;const id=m.chat.id;if(m.text==="/start")return bot.sendMessage(id,`Kerala Lottery FINAL V7 TEXT ONLY\nType 4-digit or 6-digit number.\nPhoto/OCR removed for low memory.`,kb());if(m.text==="/status")return stat(id);if(m.text==="/sync")return doSync(id);if(m.text?.startsWith("/syncurl ")){if(!isAdmin(id))return;try{const r=await syncUrl(m.text.slice(9).trim());return bot.sendMessage(id,`✅ URL synced | 4D:${r.added4} | First:${r.added1}`,kb());}catch(e){return bot.sendMessage(id,`❌ ${e.message}`);}}if(m.text){for(const v of [...m.text.matchAll(/\b(\d{4}|\d{6})\b/g)].map(x=>x[1])){const a=analyzeInput(v,new Date());if(a)await bot.sendMessage(id,fmt(a),kb());}}}
async function cb(q){const id=q.message?.chat?.id;if(!id)return;try{await bot.answerCallbackQuery(q.id);}catch{}if(q.data==="sync_today")return doSync(id);if(q.data==="status")return stat(id);}
app.get("/",(_,r)=>r.send("V7 TEXT ONLY ONLINE"));app.get("/health",(_,r)=>r.json({ok:true,...status()}));app.post(`/telegram/${secret}`,(req,res)=>{res.sendStatus(200);if(req.body?.callback_query)cb(req.body.callback_query).catch(console.error);else handle(req.body?.message).catch(console.error);});
app.listen(port,"0.0.0.0",async()=>{const u=process.env.RENDER_EXTERNAL_URL;if(u)try{await bot.setWebHook(`${u.replace(/\/$/,"")}/telegram/${secret}`);}catch{}console.log("ONLINE",status());});
