
import express from "express";import TelegramBot from "node-telegram-bot-api";import {extract} from "./ocr.js";import {loadData,analyze,status} from "./engine.js";
const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw Error("TELEGRAM_BOT_TOKEN missing");
const bot=new TelegramBot(token,{polling:false}),app=express(),port=Number(process.env.PORT||10000),secret=process.env.WEBHOOK_SECRET||"lotto-v5",max=Number(process.env.MAX_TICKETS_PER_PHOTO||10);app.use(express.json({limit:"6mb"}));loadData();
const g=v=>v==null?"Never":`${v}d`;
function fmt(x){const p=x.p4;let s=`INPUT: ${x.input}\nAS OF: ${x.asOf}\n\nLAST-4: ${x.suffix}\n365-day hits: ${p.c365}\n180-day hits: ${p.c180}\n90-day hits: ${p.c90}\n30-day hits: ${p.c30}\nAll-history hits: ${p.all}\n365-day observed frequency: ${p.rate365}%\nAll-history frequency: ${p.rateAll}%\nLast seen: ${g(p.lastGap)} ago\nFREQUENCY PROBABILITY SCORE (Historical Model): ${p.score}%\n`;const ys=Object.entries(p.yearly).map(([y,c])=>`${y}:${c}`).join(" | ");if(ys)s+=`Year-wise hits: ${ys}\n`;
if(x.e6)s+=`\nEXACT 6-DIGIT: ${x.input}\n365-day hits: ${x.e6.c365}\nAll-history hits: ${x.e6.all}\nLast seen: ${g(x.e6.lastGap)} ago\n6-Digit Frequency Score: ${x.e6.score}%\n`;
s+=`\nBOT NEARBY HISTORICAL CANDIDATES\n`;if(!x.suggestions.length)s+=`NO STRONG HISTORICAL CANDIDATE FOUND near ${x.suffix}.\n`;else x.suggestions.forEach((c,i)=>{s+=`${i+1}. ${c.s} — ${c.score}%${i===0?"  BEST":""}\n   365d:${c.c365} | 180d:${c.c180} | 90d:${c.c90} | all:${c.all} | last:${g(c.lastGap)}\n   distance:${c.dist} | digit changes:${c.ham}\n`;});return s+"\nModel % is a historical frequency score, not a guaranteed future lottery probability.";}
async function handle(m){if(!m?.chat?.id)return;const id=m.chat.id;if(m.text==="/start"){const st=status();return bot.sendMessage(id,`Kerala Lottery Frequency V5\nRows:${st.rows}\nThrough:${st.lastDate}\nType 4-digit/6-digit or send photo.`);}if(m.text==="/status"){const st=status();return bot.sendMessage(id,`ONLINE\nRows:${st.rows}\nThrough:${st.lastDate}`);}if(m.text){const vals=[...m.text.matchAll(/\b(\d{4}|\d{6})\b/g)].map(x=>x[1]).slice(0,max);for(const v of vals){const a=analyze(v,new Date());if(a)await bot.sendMessage(id,fmt(a));}return;}if(m.photo?.length){await bot.sendMessage(id,"Photo analyse cheyyunnu...");try{const f=m.photo.at(-1),url=await bot.getFileLink(f.file_id),r=await fetch(url),buf=Buffer.from(await r.arrayBuffer()),ts=await extract(buf,max);if(!ts.length)return bot.sendMessage(id,"OCR clear alla. Number manually type cheyyuka.");for(const t of ts){const a=analyze(t.number,new Date());if(a)await bot.sendMessage(id,fmt(a));}}catch(e){console.error(e);await bot.sendMessage(id,"Photo analysis error.");}}}
app.get("/",(_,r)=>r.send(`Kerala Lottery Frequency V5 ONLINE | rows=${status().rows}`));app.get("/health",(_,r)=>r.json({ok:true,...status()}));app.post(`/telegram/${secret}`,(req,res)=>{res.sendStatus(200);handle(req.body?.message).catch(console.error);});app.listen(port,"0.0.0.0",async()=>{const u=process.env.RENDER_EXTERNAL_URL;if(u){try{await bot.setWebHook(`${u.replace(/\/$/,"")}/telegram/${secret}`);}catch(e){console.error(e.message);}}console.log("ONLINE",status());});
