
import "dotenv/config"; import express from "express"; import TelegramBot from "node-telegram-bot-api"; import {extractTickets} from "./ocr.js"; import {loadData,rankTickets,dataCount} from "./analyzer.js";
const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error("TELEGRAM_BOT_TOKEN missing");
const secret=process.env.WEBHOOK_SECRET||"lottery-webhook", port=Number(process.env.PORT||10000), max=Number(process.env.MAX_TICKETS_PER_PHOTO||10);
const bot=new TelegramBot(token,{polling:false}), app=express(); app.use(express.json({limit:"5mb"})); loadData();
function report(a){if(!a.length)return"Ticket number kandethan pattiyilla.";let s="KERALA LOTTERY HISTORICAL ANALYSIS\n\n";a.forEach((x,i)=>{s+=`${i+1}. ${x.series?x.series+" ":""}${x.number}\nPattern Score: ${x.score}/100\nExact: ${x.exact} | Last4: ${x.last4} | Last3: ${x.last3} | Last2: ${x.last2}\n\n`;});return s+"Pattern Score historical statistics mathram aanu; future winning probability alla.";}
async function handle(m){const id=m.chat.id;if(m.text==="/start")return bot.sendMessage(id,`Kerala Lottery Analyzer ready.\nHistorical rows: ${dataCount()}`);if(m.text){const t=[...m.text.toUpperCase().matchAll(/\b([A-Z]{1,3})?\s*[-:]?\s*(\d{6})\b/g)].map(x=>({series:x[1]||"",number:x[2]})).slice(0,max);if(t.length)return bot.sendMessage(id,report(rankTickets(t)));}if(m.photo?.length){await bot.sendMessage(id,"Photo analyse cheyyunnu...");const f=m.photo.at(-1),link=await bot.getFileLink(f.file_id),res=await fetch(link),buf=Buffer.from(await res.arrayBuffer()),t=await extractTickets(buf,max);return bot.sendMessage(id,report(rankTickets(t)));}}
app.get("/",(_,r)=>r.send(`Kerala Lottery Analyzer ONLINE | rows=${dataCount()}`));app.get("/health",(_,r)=>r.json({ok:true,rows:dataCount()}));app.post(`/telegram/${secret}`,(req,res)=>{res.sendStatus(200);handle(req.body?.message||{}).catch(console.error);});
app.listen(port,"0.0.0.0",async()=>{const u=process.env.RENDER_EXTERNAL_URL;if(u){await bot.setWebHook(`${u}/telegram/${secret}`);console.log("Webhook set");}console.log("Online on",port);});
